openapi: "3.0.0"
info:
  title: E-commerce application
  description: 
  version: 1.1.0
  contact:
    email: shashank@shashankdutt.in
    url: https://shashankdutt.in

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
servers:
  - url: "{protocol}://localhost:4000/"
    description: 'for localhost for secure'
    variables:
        version:
          enum: 
            - v1
            - v2
        protocol:
          enum: 
            - http
            - https
          default: http

paths:
  /:
    get:
      tags:
          - Routes
      summary: Returns a Object.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: true
                  name:
                    type: string
                  Age:
                    type: integer

  /api/v1/:
    post:
      tags:
        - Auth
      summary: It's Just for registering as new user
      description: Authentications
      requestBody:
        description: User info
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary









      responses:
        '200'